from abc import ABC, abstractmethod
from typing import List, Optional
from domain.evento.evento import Evento
from domain.cliente.cliente import Cliente
from domain.entrada.entrada import Entrada

class IEventoRepo(ABC):
    @abstractmethod
    def add(self, evento: Evento) -> None: ...
    @abstractmethod
    def get(self, id_evento: int) -> Optional[Evento]: ...
    @abstractmethod
    def list_all(self) -> List[Evento]: ...
    @abstractmethod
    def update(self, evento: Evento) -> None: ...
    @abstractmethod
    def delete(self, id_evento: int) -> None: ...

class IClienteRepo(ABC):
    @abstractmethod
    def add(self, cliente: Cliente) -> None: ...
    @abstractmethod
    def get(self, id_cliente: int) -> Optional[Cliente]: ...
    @abstractmethod
    def list_all(self) -> List[Cliente]: ...
    @abstractmethod
    def update(self, cliente: Cliente) -> None: ...
    @abstractmethod
    def delete(self, id_cliente: int) -> None: ...

class IEntradaRepo(ABC):
    @abstractmethod
    def add(self, entrada: Entrada) -> None: ...
    @abstractmethod
    def get(self, id_entrada: int) -> Optional[Entrada]: ...
    @abstractmethod
    def find_by_evento_cliente(self, id_evento: int, id_cliente: int) -> Optional[Entrada]: ...
    @abstractmethod
    def list_by_evento(self, id_evento: int): ...
    @abstractmethod
    def update(self, entrada: Entrada) -> None: ...